Add objective_see_install function
The Objective-See applications are packaged as .app installers.

The existing install_applications function can not be used.

The binary inside the .app must be executed as sudo with -install as an argument.

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -440,17 +440,54 @@ function install_application {
 }
 
 
+function objective_see_install {
+
+  local application_name=${1:-"unset"}
+  local downloaded_file_path=${2:-"unset"}
+  local downloaded_file_name
+  file_name=$(echo "${downloaded_file_path}" | awk -F '/' '{print $(NF)}')
 
 
-
+  if [[ "${application_name}" == "unset" ]]; then 
+    echo "[❌] 'application_name' var not set"
     exit 1
 
+  elif [[ "${downloaded_file_path}" == "unset" ]]; then
+    echo "[❌] 'downloaded_file_path' var not set"
     exit 1
-  fi
+  fi 
 
+  echo "[🍺] Attempting to unzip ${downloaded_file_path}"
+  if unzip -qa "${downloaded_file_path}" -d "${HOME}/Downloads"; then
+    # Attempt to unzip
+    echo "[✅] Successfully unzipped ${downloaded_file_name}"
   else
+    echo "[❌] Failed to unzip ${downloaded_file_name}"
     exit 1
   fi
+
+  echo "[🍺] Attempting to validated the signature on ${application_name}_Installer.app"
+  if pkgutil --check-signature "${HOME}/Downloads/${application_name}_Installer.app"; then
+    # Check the .app is correctly signed
+    echo "[✅] Successfully validated the signature on ${application_name}_Installer.app"
+  else
+    echo "[❌] Failed to validate the signature on ${application_name}_Installer.app"
+    exit 1
+  fi
+
+  (
+    # Execute in a subshell so the working directory is not permanantly changed
+    cd "${HOME}/Downloads" || exit
+
+    echo "[⚠️ ] Password required to install ${application_name}"
+
+    if sudo bash -c "./${application_name}_Installer.app/Contents/MacOS/${application_name} -install"; then 
+      echo "[✅] Successfully installed ${application_name}"
+    else
+      echo "[❌] Failed to install ${application_name}"
+      exit 1
+    fi
+  )
 
 }
 
