Remove mas_helper
See: https://github.com/mas-cli/mas/issues/164

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -63,7 +63,6 @@ function usage {
 # verify_signature
 # install_application
 # objective_see_install
-# mas_helper
 # check_sudo
 # run_test
 
@@ -325,21 +324,6 @@ function objective_see_install {
       fi
     fi
   )
-}
-
-
-function mas_helper {
-
-if ! brew install mas 2>/dev/null; then
-  echo "[❌] Failed to install mas"
-  return 1
-fi
-
-if ! mas account >/dev/null; then
-  echo "[❌] Not signed into the App Store"
-  echo "[🍺] Sign in then rerun './bittersweet brewfile'"
-  return 1
-fi 
 }
 
 
@@ -937,6 +921,15 @@ function install_brewfile {
   local HOMEBREW_BREWFILE=${1:-"${HOME}/Documents/Projects/dotfiles/Brewfile"}
   export HOMEBREW_BREWFILE="${HOMEBREW_BREWFILE}"
 
+  echo "[🍺] Installing mas"
+
+  if ! brew install mas 2>/dev/null; then
+    echo "[❌] Failed to install mas"
+    return 1
+  else
+    echo "[✅] Installed mas"
+  fi
+
   echo "[🍺] Exported HOMEBREW_BREWFILE=${HOMEBREW_BREWFILE}"
   echo "[🍺] Installing Homebrew packages from Brewfile"
   
@@ -1050,7 +1043,6 @@ function main {
 
   elif [[ "${cmd}" == "brewfile" ]]; then
     local HOMEBREW_BREWFILE=${2:-"${HOME}/Documents/Projects/dotfiles/Brewfile"}
-    mas_helper
     install_brewfile "${HOMEBREW_BREWFILE}"
 
   elif [[ "${cmd}" == "shell" ]]; then
@@ -1081,7 +1073,6 @@ function main {
     install_blockblock
     install_oversight
     install_brew
-    mas_helper
     install_brewfile "${HOMEBREW_BREWFILE}"
     lockdown "fix" "force"
     change_shell
