install_dotfiles: Check if dir already exists
Before trying to `mkdir -p` `$HOME/.ssh` and `$HOME/. gnupg` check if they already exist.

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -485,10 +485,12 @@ function install_dotfiles {
     if [ -d "${dir_name}" ] ; then
       dir_name_base=$(basename "${dir_name}");
 
-      if mkdir -p "${HOME}/${dir_name_base}" ; then
-        echo "[✅] Successfully created ${HOME}/${dir_name_base}"
-      else
-        echo "[❌] Failed to create ${HOME}/${dir_name_base}"
+      if ! [ -d "${HOME}/${dir_name_base}" ]; then
+        if mkdir -p "${HOME}/${dir_name_base}" ; then
+          echo "[✅] Successfully created ${HOME}/${dir_name_base}"
+        else
+          echo "[❌] Failed to create ${HOME}/${dir_name_base}"
+        fi
       fi
     else
       echo "[❌] ${dir_name} does not exists"
