change_shell: Refactor

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -903,25 +903,32 @@ function change_shell {
   
   if [[ "${SHELL}" == "${new_shell}" ]]; then
     echo "[✅] Current shell is already '${new_shell}'"
-  else
+    return 0
+  fi
 
-    get_sudo "to change shell"
+  get_sudo "to change shell"
 
-    if [ -e "${new_shell}" ]; then
-      sudo bash -c "echo ${new_shell} >> /etc/shells"
-      # !! SUDO !!
-      # Add new shell to list of allowed shells
-      # https://unix.stackexchange.com/a/4833/271903
-      if chsh -s "${new_shell}"; then
-      # Change $USER shell
-        echo "[✅] Successfully change default shell to ${new_shell}"
-      else  
-        echo "[❌] Failed to change default shell to ${new_shell}"
-      fi
-    else
-      echo "[❌] Failed to change shell as '${new_shell}' does not exist"
-    fi
-  fi   
+  if [[ ! -e "${new_shell}" ]]; then
+    echo "[❌] Failed to change shell as '${new_shell}' does not exist"
+    return 1
+  fi
+
+  if ! sudo bash -c "echo ${new_shell} >> /etc/shells"; then
+    # !! SUDO !!
+    # Add new shell to list of allowed shells
+    # https://unix.stackexchange.com/a/4833/271903
+    echo "[❌] Failed to add ${new_shell} to /etc/shells"
+    return 1
+  fi
+  
+  if chsh -s "${new_shell}"; then
+  # Change $USER shell
+    echo "[✅] Successfully change default shell to ${new_shell}"
+    return 0
+  else  
+    echo "[❌] Failed to change default shell to ${new_shell}"
+    return 1
+  fi
 }
 
 
