install_sublime_text: Unnest if statements

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -641,46 +641,45 @@ function install_gpgtools {
 
 function install_sublime_text {
 
-  if [ ! -d "/Applications/Sublime Text.app" ]; then
-
-    echo "[🍺] Installing Sublime Text"
-
-    local latest_build  
-    latest_build="$(curl -s https://www.sublimetext.com/3 \
-                | grep "Version:" \
-                | awk '{print ($4+0)}')"
-    # Get the latest build string
-    # grep "Version:" \ : <p class="latest"><i>Version:</i> Build 3143</p>
-    # awk '{print $4}' : 3143</p>
-    # awk '{print ($4+0)}' : 3143
-    # ($4+0) converts captured string to numeric
-    local dmg_name="Sublime Text Build ${latest_build}.dmg"
-    local dmg_download_path="${HOME}/Downloads/${dmg_name}"
-    local dmg_mount_point="/Volumes/Sublime Text" 
-    
-    download_application "${dmg_download_path}" "https://download.sublimetext.com/Sublime%20Text%20Build%20${latest_build}.dmg"
-
-    install_application "Sublime Text" "${dmg_download_path}"
-
-    ## Install config files
-    echo "[🍺] Installing Sublime Text config files"
-
-    if mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Packages/"; then
-      echo "[✅] Successfully created ~/Library/Application Support/Sublime Text 3/Packages/"
-    else
-      echo "[❌] Failed to create ~/Library/Application Support/Sublime Text 3/Packages/"
-      exit 1
-    fi 
-
-    if cp -r "Sublime Text 3/Packages/User" "$HOME/Library/Application Support/Sublime Text 3/Packages"; then
-      echo "[✅] Successfully installed Sublime Text config files"
-    else
-      echo "[❌] Failed to install Sublime Text config files"
-      exit 1
-    fi
-
-  else 
+  if [[ -d "/Applications/Sublime Text.app" ]]; then
     echo "[🍺] Sublime Text already installed"
+    return 0
+  fi
+
+  echo "[🍺] Installing Sublime Text"
+
+  local latest_build  
+  latest_build="$(curl -s https://www.sublimetext.com/3 \
+              | grep "Version:" \
+              | awk '{print ($4+0)}')"
+  # Get the latest build string
+  # grep "Version:" \ : <p class="latest"><i>Version:</i> Build 3143</p>
+  # awk '{print $4}' : 3143</p>
+  # awk '{print ($4+0)}' : 3143
+  # ($4+0) converts captured string to numeric
+  local dmg_name="Sublime Text Build ${latest_build}.dmg"
+  local dmg_download_path="${HOME}/Downloads/${dmg_name}"
+  local dmg_mount_point="/Volumes/Sublime Text" 
+  
+  download_application "${dmg_download_path}" "https://download.sublimetext.com/Sublime%20Text%20Build%20${latest_build}.dmg"
+
+  install_application "Sublime Text" "${dmg_download_path}"
+
+  ## Install config files
+  echo "[🍺] Installing Sublime Text config files"
+
+  if mkdir -p "$HOME/Library/Application Support/Sublime Text 3/Packages/"; then
+    echo "[✅] Successfully created ~/Library/Application Support/Sublime Text 3/Packages/"
+  else
+    echo "[❌] Failed to create ~/Library/Application Support/Sublime Text 3/Packages/"
+    exit 1
+  fi 
+
+  if cp -r "Sublime Text 3/Packages/User" "$HOME/Library/Application Support/Sublime Text 3/Packages"; then
+    echo "[✅] Successfully installed Sublime Text config files"
+  else
+    echo "[❌] Failed to install Sublime Text config files"
+    exit 1
   fi
 }
 
