bittersweet: Update install_rocket
- Add check for Rocket.app
- Wrap all actions inside the check
- Now makes use of install_application

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -567,51 +567,32 @@ function install_tower {
 
 install_rocket () {
 
-  echo "[🍺] Installing Rocket 🚀"
+  if [ ! -d "/Applications/Rocket.app" ]; then
 
-  local url
-  local dmg_name
-  local dmg_download_path
-  local dmg_mount_point
+    echo "[🍺] Installing Rocket 🚀"
 
-  url="$(curl -s http://matthewpalmer.net/rocket/ | grep "Download" | awk -F '"' '{print $4}')"
-  dmg_name="Rocket.dmg"
-  dmg_download_path="${HOME}/Downloads/${dmg_name}"
-  local dmg_mount_point="/Volumes/Rocket" 
+    local url
+    local dmg_name
+    local dmg_download_path
+    local dmg_mount_point
 
-  if curl -L -o "${dmg_download_path}" "${url}" ; then 
-    # Download 
-    echo "[✅] Successfully downloaded ${dmg_name}"
-  else
-    echo "[❌] Failed to download ${dmg_name}"
-    exit 1
-  fi
+    url="$(curl -s https://matthewpalmer.net/rocket/ | grep "Download" | awk -F '"' '{print $4}')"
+    dmg_name="Rocket.dmg"
+    dmg_download_path="${HOME}/Downloads/${dmg_name}"
+    dmg_mount_point="/Volumes/Rocket" 
 
-  echo "[🍺] Attempting to mount ${dmg_download_path}"
-  if hdiutil attach -quiet "${dmg_download_path}" ; then
-  # Attempt to mount the DMG 
-    echo "[✅] Successfully mounted ${dmg_name}"
-  else
-    echo "[❌] Failed to mount ${dmg_name}"
-    exit 1
-  fi  
+    if curl -L -o "${dmg_download_path}" "${url}"; then 
+      # Download 
+      echo "[✅] Successfully downloaded ${dmg_name}"
+    else
+      echo "[❌] Failed to download ${dmg_name}"
+      exit 1
+    fi
 
-  echo "[🍺] Attempting to validated the signature on Rocket.app"
-  if pkgutil --check-signature "${dmg_mount_point}/Rocket.app" ; then
-  # Check Rocket.app is correctly sogned
-    echo "[✅] Successfully validated the signature on Rocket.app"
-  else
-    echo "[❌] Failed to validate the signature on Rocket.app"
-    exit 1
-  fi
+    install_application "Rocket" "${dmg_download_path}"
 
-  echo "[🍺] Attempting to copy Rocket.app into /Applications"
-  if cp -Ri "${dmg_mount_point}/Rocket.app" "/Applications" ; then
-  # Attempt to copy Rocket.app into /Applications 
-    echo "[✅] Successfully installed Rocket 🚀"
-  else
-    echo "[❌] Failed to install Rocket 🚀"
-    exit 1
+  else 
+    echo "[🍺] Rocket already installed"
   fi
 }
 
