Add open_system_prefernces_mdm_profile
See 4f54d1e9ccfea8dfdfc80b3394ba48c536070023 for the inital MDM profile (.mobileconfig)

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -46,6 +46,7 @@ function usage {
   echo "  brewfile              - Install Homebrew packages from Brewfile"
   echo "  compinit              - Fix permissions on zsh completion directory /usr/local/share"
   echo "  shell                 - Change shell to bash as installed by Brew"
+  echo "  mdmprofile            - Open System Prefernces to install MDM Profile"
 
   echo -e "\\n  ${RED}hailmary${RESET}              - ${BOLD}Run every function${RESET} in order listed above"
 
@@ -1005,6 +1006,25 @@ function change_shell {
 }
 
 
+function open_system_prefernces_mdm_profile {
+  # open_system_prefernces_mdm_profile
+  # As of macOS Big Sur (11) /usr/bin/profiles can no longer install .mobileconfig profiles
+  # MDM Profiles must be installed via the GUI via System Preferences > Profiles
+  # However we can semi automate this process
+  #   See: https://www.alansiu.net/2021/01/06/semi-automating-profile-installation-in-big-sur/
+
+  local -r profile_file_name="machos-dotfile.mobileconfig"
+  local -r profile_display_name="0xmachos Dotfiles Profile"
+
+  if ! open /System/Library/PreferencePanes/Profiles.prefPane "profiles/${profile_file_name:?}"; then
+    echo "[❌] Failed to open System Prefernces > Profiles with ${profile_display_name}"
+    return 1
+  fi
+
+  echo "[⚠️ ] Go to System Prefernces > Profiles and install ${profile_display_name}"
+}
+
+
 function main {
 
   check_os_compatibility
@@ -1072,6 +1092,9 @@ function main {
     shell)
       change_shell
       ;;
+    mdmprofile)
+      open_system_prefernces_mdm_profile
+      ;;
     test)
       run_test
       ;;
@@ -1098,6 +1121,7 @@ function main {
       install_brewfile
       zsh_compinit_fix
       change_shell
+      open_system_prefernces_mdm_profile
       ;;
     *)
       usage
