Add enable_touchid_sudo

diff --git a/bittersweet b/bittersweet
--- a/bittersweet
+++ b/bittersweet
@@ -36,6 +36,7 @@ function usage {
   echo "Usage:"
   echo "  defaults              - Write new system and application default settings"
   echo "  dotfiles              - Symlink various config files into ${HOME}"
+  echo "  sudotouch             - Enable TouchID to sudo"
   echo "  gpgtools              - Install GPGTools"
   echo "  sublimetext           - Install Sublime Text"
   echo "  tower                 - Install Tower"
@@ -569,6 +570,22 @@ function install_dotfiles {
 }
 
 
+function enable_touchid_sudo {
+  if ! grep -q 'pam_tid.so' /etc/pam.d/sudo; then
+    if sudo ex -s -c '2i|auth       sufficient     pam_tid.so' -c x! -c x! /etc/pam.d/sudo; then
+      # Invoke Vim in ex mode
+      # Select line 2, enter insert mode, insert that text write changes and exit
+      # Need to exit twice to get passed the read only file warning
+      echo "[✅] TouchID Sudo Enabled"
+    else
+      echo "[❌] Failed to enable TouchID Sudo"
+    fi
+  else
+    echo "[✅] TouchID Sudo Already Enabled"
+  fi
+}
+
+
 function install_gpgtools {
   
   if ! [ -x "$(command -v gpg2)" ]; then
@@ -948,6 +965,9 @@ function main {
   elif [[ "${cmd}" == "dotfiles" ]]; then
     install_dotfiles
 
+  elif [[ "${cmd}" == "sudotouch" ]]; then
+    enable_touchid_sudo
+
   elif [[ "${cmd}" == "gpgtools" ]]; then 
     install_gpgtools
 
@@ -991,6 +1011,7 @@ function main {
 
     write_defaults
     install_dotfiles
+    enable_touchid_sudo
     install_gpgtools
     install_sublime_text
     install_tower
