Update

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,10 +1,11 @@
 #!/bin/bash
-# dotfiles/bin/test
+# dotfiles/test
 
-# test.sh
-#   Find shell scripts then run shellcheck 
+# test
+#   Find bash scripts then run shellcheck
 #   Adapted from jessfraz/dotfiles/bin/test.sh
 #   https://github.com/jessfraz/dotfiles/blob/master/test.sh
+
 
 set -euo pipefail
 # -e exit if any command returns non-zero status code
@@ -12,14 +13,26 @@ set -euo pipefail
 # -o pipefail force pipelines to fail on first non-zero status code
 
 
-FAIL="\\033[1;31mFAIL\\033[0m"
-INFO="\\033[1;36mINFO\\033[0m"
-PASS="\\033[1;32mPASS\\033[0m"
+### Define Colours ###
+tput sgr0; 
+# reset colors
+
+readonly RESET=$(tput sgr0)
+readonly BOLD=$(tput bold)
+
+readonly RED=$(tput setaf 1)
+readonly GREEN=$(tput setaf 64)
+readonly BLUE=$(tput setaf 4)
+### END Colours ###
+
+FAIL="${RED}FATAL${RESET}"
+PASS="${GREEN}PASS${RESET}"
+INFO="${BLUE}INFO${RESET}"
 
 
-check_shellcheck () {
+function check_shellcheck {
 
-  if ! [ -x "$(command -v "${shellcheck_binary}")" ]; then 
+  if ! [ -x "$(command -v shellcheck)" ]; then
     echo -e "[${FAIL}] shellcheck not installed"
     echo -e "[${INFO}] macOS: brew install shellcheck"
     echo -e "[${INFO}] Linux: apt install shellcheck"
@@ -28,37 +41,27 @@ check_shellcheck () {
 }
 
 
-lint_shell_files () {
+function lint_shell_files {
 
-  for f in $(find . -type f -not -iwholename '*.git*' \
-        -not -iwholename '*venv*' \
-        | sort -u); do
-    # Find all regular files in source directory
-
-    if file "${f}" | grep --quiet "shell" ; then
-      # Find shell files
-      
-      if "${shellcheck_binary}" "${f}" ; then
-        # Run shellcheck on the file
-        echo -e "[${PASS}] Sucessfully analysed ${f}"
-      else
-        echo -e "[${FAIL}] Failed to analyse ${f}"
-        ERRORS+=("${f}")
-        # If shellcheck fails add failing file name to array
-      fi
+  for file in $(find . -type f -not -iwholename '*.git*' \
+                -not -iwholename '*venv*' \
+                | sort -u); do
+            # Find all regular files in source directory
+            # ignore any files in .git and venv directories 
     
-    elif file "${f}" | grep --quiet "bash" ; then
-      # Find shell files
-      # Running file on a script with the shebang "#!/usr/bin/env ..." returns
-      # "a /usr/bin/env bash script, ASCII text executable" rather than
+    if file "${file}" | grep --quiet "shell" || file "${file}" | grep --quiet "bash" ; then
+      # Find bash scripts
+      # Running file on a script with the shebang "#!/usr/bin/env bash" returns
+      # "a /usr/bin/env bash script, ASCII text executable"
+      # Versus a script with the shebang "#!/bin/bash" which returns
       # "Bourne-Again shell script, ASCII text executable"
       
-      if "${shellcheck_binary}" "${f}" ; then
+      if shellcheck "${file}" ; then
         # Run shellcheck on the file
-        echo -e "[${PASS}] Sucessfully analysed ${f}"
+        echo -e "[${PASS}] Sucessfully linted ${file}"
       else
-        echo -e "[${FAIL}] Failed to analyse ${f}"
-        ERRORS+=("${f}")
+        echo -e "[${FAIL}] Failed to lint ${file}"
+        ERRORS+=("${file}")
         # If shellcheck fails add failing file name to array
       fi
     fi
@@ -66,17 +69,9 @@ lint_shell_files () {
 }
 
 
-main () {
+function main {
 
   ERRORS=()
-
-  set +u
-  if [[ "${TRAVIS}" == "true" ]]; then
-    shellcheck_binary="/usr/bin/shellcheck"
-  else
-    shellcheck_binary="shellcheck"
-  fi
-  set -u
 
   check_shellcheck
   lint_shell_files
@@ -86,8 +81,8 @@ main () {
     echo -e "[${PASS}] No errors, hooray"
     exit 0
   else
-    # If errors print the names of files which failed
-    echo -e "[${FAIL}] These files failed analysis: ${ERRORS[*]}"
+    # If ERRORS not empty, print the names of files which failed
+    echo -e "[${FAIL}] These files failed linting: ${ERRORS[*]}"
     exit 1
   fi
 }
