Lint PlistsL Fix indentation

diff --git a/.github/workflows/Shellcheck.yml b/.github/workflows/Shellcheck.yml
--- a/.github/workflows/Shellcheck.yml
+++ b/.github/workflows/Shellcheck.yml
@@ -79,17 +79,17 @@ jobs:
     steps:
     - name: Lint
       run: |
-      declare -a FILES
+        declare -a FILES
 
-      while IFS=$'\n' read -r file; do 
-        FILES+=("${file}");
-      done < <(/usr/bin/find . -maxdepth 4 \
-              -type f \
-              \( -name "*.plist" -o -name "*.mobileconfig" \))
+        while IFS=$'\n' read -r file; do 
+          FILES+=("${file}");
+        done < <(/usr/bin/find . -maxdepth 4 \
+                -type f \
+                \( -name "*.plist" -o -name "*.mobileconfig" \))
 
-      for file in "${FILES[@]}"; do
-        if ! /usr/bin/plutil -lint "${file}" ; then
-          echo "[FAIL] $(/usr/bin/basename "${file}")"
-          ERRORS+=("${file}")
-        fi
-      done
+        for file in "${FILES[@]}"; do
+          if ! /usr/bin/plutil -lint "${file}" ; then
+            echo "[FAIL] $(/usr/bin/basename "${file}")"
+            ERRORS+=("${file}")
+          fi
+        done
