Add Lint Plists job

diff --git a/.github/workflows/Shellcheck.yml b/.github/workflows/Shellcheck.yml
--- a/.github/workflows/Shellcheck.yml
+++ b/.github/workflows/Shellcheck.yml
@@ -72,3 +72,24 @@ jobs:
           echo "[FAIL] These files failed linting: ${ERRORS[*]}"
           exit 1
         fi
+  
+  Lint Plists:
+    runs-on: macos-latest
+
+    steps:
+    - name: Lint
+      run: |
+      declare -a FILES
+
+      while IFS=$'\n' read -r file; do 
+        FILES+=("${file}");
+      done < <(/usr/bin/find . -maxdepth 4 \
+              -type f \
+              \( -name "*.plist" -o -name "*.mobileconfig" \))
+
+      for file in "${FILES[@]}"; do
+        if ! /usr/bin/plutil -lint "${file}" ; then
+          echo "[FAIL] $(/usr/bin/basename "${file}")"
+          ERRORS+=("${file}")
+        fi
+      done
